### ISSUE TITLE
Implement Minimum Viable Bot

### ISSUE THREAD

**Issue by haikoschol** [samurang87/availabot#13]
1. Read up on "inline" vs the other kind of Telegram bot and decide which one we want.

2. Find out what HTTP interface Telegram requires and implement it with the following logic (preferrably using only the standard library):
Whenever the bot receives any message, it looks up two predefined calendars and calculates availability for them (using hard-coded access tokens).

N.B. Make sure to only respond to the users whose calendar credentials the bot has access to.

**Comment by samurang87** [comment]
Let's try the inline one
